spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.62.0.129:3306/eblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    # Druid ?????
  freemarker:
    cache: false
    template-loader-path: classpath:/templates/
    suffix: .ftl
    prefer-file-system-access: false
    settings:
      classic_compatible: true
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##
  redis:
    host: 10.62.0.129
    port: 6379
    password: 123456

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8081
